Frontend dev
volkovalexandra11/random-coffee pull request #1
Opened 2022-12-10 19:39 UTC by volkovalexandra11

Сделала ПР, чтобы поревьювить его
Тыкать буду и в свои ошибки в том числе

2022-12-10 19:53 UTC, volkovalexandra11 reviewed
В целом все ок, но надо будет пофиксить всякое

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/App.test.tsx
> +import React from 'react';
Такое можно не писать уже)

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/filter/filter.tsx
> +    setOtherState: (value: number) => void;
Не говорящее ни о чем название

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/filter/filter.tsx
> +    setState: (value: number) => void;
Лучше такое не использовать

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/filter/filter.tsx
> +    function MakeFilter(stateNow: number, setState: (value: number) => void, setOtherState: (value: number) => void) {
Лучше все константами делать:
const myFunc = () => {...}

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/filter/filter.tsx
> +    function MakeFilter(stateNow: number, setState: (value: number) => void, setOtherState: (value: number) => void) {
Получается слишком длинно, нужны маски

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/group-create-form/group-create-form.tsx
> +    const navigate = useNavigate();
Респект

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/group-table/group-table.tsx
> +// import SearchIcon from '@skbkontur/react-icons/search';
Лучше такое дропать, а не комментить

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/group-table/group-table.tsx
> +import {Button} from '@skbkontur/react-ui';
Порядок импортов поехал

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/login-form/login-form.tsx
> +import { ChangeEvent, MouseEvent, FC, useState } from 'react';
Этот файл надо грохнуть

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/login-with-google/login-with-google.module.scss
> +.wrapper {
И этот файлик тоже грохнуть

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/login-with-google/login-with-google.tsx
> +import { CredentialResponse, GoogleLogin } from '@react-oauth/google';
Переписать на модалочку

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/nav-bar/nav-bar.tsx
> +	function renderModal() {
Делать все константами

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/nav-bar/nav-bar.tsx
> +	const navigate = useNavigate();
Унести наверх

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/search/search.tsx
> +
зочьем пустая строка

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/search/search.tsx
> +export const SearchGroup: FC<Props> =({groups, setGroups}) =>{
Бахнуть пробелов бы
Могу помочь настроить в иде

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/search/search.tsx
> +    function sortDate(paramToSort: string) : void{
Сделать ее константой и перетащить выше, чем юзЭффект. А еще лучше унести в какие-нить utils/helpers

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/search/search.tsx
> +            setGroups(copyData);
Что-то, что приходит через пропсы, — это коллбэк. Принято называть их onSetGroups, чтобы по названию было понятно, что это не функции изменения состояния

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/components/signup-form/signup-form.tsx
> +import { ChangeEvent, MouseEvent, FC, useState } from 'react';
Дропнуть этот файл

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/mock/mock-group-list.ts
> +	},
Давайте будем удалять код, а не комментировать

2022-12-10 19:53 UTC, volkovalexandra11 commented on random-coffee-front/src/setupTests.ts
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
Мы вряд ли будем писать тесты, поэтому можно дропнуть

2022-12-12 11:36 UTC, volkovalexandra11 commented on random-coffee-front/src/App.test.tsx
> +import { render, screen } from '@testing-library/react';
Дропнуть бы

2022-12-12 11:40 UTC, aynug24 requested changes
.idea в коммите? Ладно не node_modules

2022-12-12 12:16 UTC, aynug24 approved these changes

2022-12-12 12:31 UTC, merged